### ISSUE TITLE
pass in config

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-views#2]
refactor a bit to be able to pass in the entire route config instead of just cache

**Comment by jgallen23** [comment]
I need to be able to config per route.  it looks like this is set up to do all routes.  can you confirm?

**Comment by dawnerd** [comment]
yeah it's global now, wouldn't be hard at all to fix

**Comment by dawnerd** [comment]
@jgallen23 Would you also want to define global route config options?

**Comment by jgallen23** [comment]
not as important

**Comment by dawnerd** [comment]
can't npm publish but it's all ready as 1.0.0
